version: '3.4'
services:
  compile:
    extends:
      file: common.yml
      service: base
    command: 'colcon build --symlink-install'

  demo:
    extends:
      file: common.yml
      service: x11_base
      # service: x11_gpu  # use this one if you want to use the GPU
    depends_on:
      compile:
        condition: service_completed_successfully
    command: 'ros2 launch fira_hackathon_demo demo.launch.py'

  challenge1:
    extends:
      service: demo
    profiles: [chal1]
    command: 'ros2 launch fira_hackathon_demo challenge1.launch.py'

  challenge2:
    extends:
      service: demo
    profiles: [chal2]
    command: 'ros2 launch fira_hackathon_demo challenge2.launch.py'

  challenge3:
    extends:
      service: demo
    profiles: [chal3]
    command: 'ros2 launch fira_hackathon_demo challenge3.launch.py'
